# Generated by Django 4.2.7 on 2023-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codVideojuego', models.IntegerField(default=4)),
                ('codUsuario', models.IntegerField(default=4)),
                ('cantidadvdj', models.IntegerField(default=4)),
                ('listadeseos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('objetivo', models.CharField(max_length=150)),
                ('edadRecomendada', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpresa', models.IntegerField(default=5)),
                ('sistemaPlataforma', models.IntegerField(default=5)),
                ('codGenero', models.IntegerField(default=5)),
                ('sipnosis', models.TextField(max_length=150)),
                ('fechaSalida', models.DateField()),
                ('valoracion', models.IntegerField(default=10)),
                ('comentarios', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
