# Generated by Django 4.2.7 on 2023-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codVideojuego', models.IntegerField(default=4)),
                ('nombreJuego', models.CharField(max_length=50)),
                ('codUsuario', models.IntegerField(default=4)),
                ('cantidadvdj', models.IntegerField(default=4)),
                ('listadeseos', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='listadeseos',
        ),
    ]
