# Generated by Django 4.2.7 on 2023-11-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerworld', '0002_listadeseos_remove_biblioteca_listadeseos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='codVideojuego',
            field=models.IntegerField(default=4),
        ),
    ]
