# Generated by Django 4.2.7 on 2024-01-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerworld', '0003_videojuego_codvideojuego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='edadRecomendada',
            new_name='edadrecomendada',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='objetivo',
            new_name='publicoobjetivo',
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='codGenero',
            new_name='codempresa',
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='idEmpresa',
            new_name='codgenero',
        ),
    ]
